services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5187:5187"

    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=fizzbuzz;Username=postgres;Password=password"
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: postgresdb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: fizzbuzz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
