services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_BASE_URL: "http://localhost:8080"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5187:5187"

    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=fizzbuzz;Username=postgres;Password=password"
    depends_on:
      - db
      - redis_db

  redis_db:
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    image: postgres:17
    container_name: postgresdb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: fizzbuzz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
